Update package.json | FIX Error: tsx must be loaded with --import instead of --loader
Debugger listening on ws://127.0.0.1:9229/8403c7b3-f5f0-4afa-9f36-f1d9bca02b29
For help, see: https://nodejs.org/en/docs/inspector

node:internal/process/esm_loader:34
internalBinding('errors').triggerUncaughtException(
^
Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0 and v18.19.0
at z (file:///home/runner/aterbot-1/node_modules/.pnpm/tsx@4.7.1/node_modules/tsx/dist/esm/index.mjs:1:1773)
at Hooks.addCustomLoader (node:internal/modules/esm/hooks:204:24)
at Hooks.register (node:internal/modules/esm/hooks:170:16)
at async initializeHooks (node:internal/modules/esm/utils:283:5)
at async customizedModuleWorker (node:internal/modules/esm/worker:104:24)

Node.js v20.12.2